### ISSUE TITLE
fave colors :3

### ISSUE THREAD

**Issue by honey-toast** [lotusware/honey-toast#1]
background: rgb(104,167,224);
background: -moz-linear-gradient(155deg, rgba(104,167,224,1) 0%, rgba(255,149,204,1) 43%, rgba(255,227,151,1) 92%);
background: -webkit-linear-gradient(155deg, rgba(104,167,224,1) 0%, rgba(255,149,204,1) 43%, rgba(255,227,151,1) 92%);
background: linear-gradient(155deg, rgba(104,167,224,1) 0%, rgba(255,149,204,1) 43%, rgba(255,227,151,1) 92%);
filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#68a7e0",endColorstr="#ffe397",GradientType=1);

**Comment by lotusware** [comment]
Added brand guidelines to the README
